# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
version: 1

metadata {
  timestamp {
    seconds: 1754424907
    nanos: 0
  }
}

components {
  type: CLASSIFICATION_LIBRARY
  bom_ref: "component-1"
  name: "example-lib"
  version: "1.2.3"

}

// continue here
