# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:bcb403ae-91fa-436e-bc93-84d1078cdeed"
metadata: {
  properties: {
    value: "missing a name"
  }
  properties: {
    # no name and no value
  }
}
components: {
  type: CLASSIFICATION_LIBRARY
  name: "acme-library"
  version: "1.0.0"
  licenses: {
    license: {
      id: "Apache-2.0"
      properties: {
        value: "missing a name"
      }
      properties: {
        # no name and no value
      }
    }
  }
  properties: {
    value: "missing a name"
  }
  properties: {
    # no name and no value
  }
}
services: {
  bom_ref: "b2a46a4b-8367-4bae-9820-95557cfe03a8"
  group: "org.partner"
  name: "Stock ticker service"
  endpoints: "https://partner.org/api/v1/stock"
  properties: {
    value: "missing a name"
  }
  properties: {
    # no name and no value
  }
}
