# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components: {
  type: CLASSIFICATION_APPLICATION
  name: "dummy"
  description: "this component has an external reference with properties"
  external_references: {
    type: EXTERNAL_REFERENCE_TYPE_COMPONENT_ANALYSIS_REPORT
    url: "http://example.com/extref/component-analysis-report"
    properties: {
      name: "author"
      value: "John Doe"
    }
    properties: {
      name: "timestamp"
      value: "2025-01-27T12:27:26Z"
    }
  }
}
