# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  name: "Foo"
  description: "extraneous with version range constraints"
  isExtraneous: true
  versionRange: "vers:pypi/0.0.0|0.0.1|0.0.2|0.0.3|1.0|2.0pre1"
}
