# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_APPLICATION
  publisher: "Acme Inc"
  group: "com.acme"
  name: "tomcat-catalina"
  version: "9.0.14"
  description: "Modified version of Apache Catalina"
  scope: SCOPE_REQUIRED
  licenses {
    expression_detailed {
      bom_ref: "my-license"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
      expression: "EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0"
      details {
        license_identifier: "EPL-2.0"
        text {
          value: "Eclipse Public License - v 2.0\n\n    THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE\n    PUBLIC LICENSE (\"AGREEMENT\"). ANY USE, REPRODUCTION OR DISTRIBUTION\n    OF THE PROGRAM CONSTITUTES RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT..."
        }
      }
      details {
        license_identifier: "GPL-2.0 WITH Classpath-exception-2.0",
        text {
          content_type: "text/plain",
          value: "                    GNU GENERAL PUBLIC LICENSE\n                       Version 2, June 1991\n\n Copyright (C) 1989, 1991 Free Software Foundation, Inc.,\n <https://fsf.org/>\n Everyone is permitted to copy and distribute verbatim copies\n of this license document, but changing it is not allowed...\n\n...\n\nLinking this library statically or dynamically with other modules is making a combined work based on this library..."
        }
      }
    }
  }
  purl: "pkg:maven/com.acme/tomcat-catalina@9.0.14?packaging=jar"
}
