# proto-file: schema/bom-1.6.proto
# proto-message: Bom

spec_version: "1.6"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_APPLICATION
  author: "Acme Super Heros"
  name: "Acme Application"
  version: "9.1.1"
  swid {
    tag_id: "swidgen-242eb18a-503e-ca37-393b-cf156ef09691_9.1.1"
    name: "Acme Application"
    version: "9.1.1"
  }
}
