# proto-file: schema/bom-1.6.proto
# proto-message: Bom

spec_version: "1.6"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  bom_ref: "library-a"
  name: "library-a"
  version: "1.0.0"
}
components {
  type: CLASSIFICATION_LIBRARY
  bom_ref: "library-b"
  name: "library-b"
  version: "1.0.0"
}
components {
  type: CLASSIFICATION_LIBRARY
  bom_ref: "library-c"
  name: "library-c"
  version: "1.0.0"
}
dependencies {
  ref: "library-a"
}
dependencies {
  ref: "library-b"
  dependencies {
    ref: "library-c"
  }
}
