# proto-file: schema/bom-1.6.proto
# proto-message: Bom

spec_version: "1.6"
version: 1
serial_number: "urn:uuid:ed5c5ba0-2be6-4b58-ac29-01a7fd375123"
components {
  type: CLASSIFICATION_MACHINE_LEARNING_MODEL
  bom_ref: "huggingface.co-meta-llama-Llama-2-7b"
  group: "meta-llama"
  name: "Llama-2-7b"
  publisher: "meta"
  supplier {
    name: "Hugging Face"
  }
  external_references {
    type: EXTERNAL_REFERENCE_TYPE_DISTRIBUTION
    url: "https://huggingface.co/meta-llama/Llama-2-7b"
  }
  modelCard {
    considerations {
      environmentalConsiderations {
        energyConsumptions {
          activity: ACTIVITY_TYPE_TRAINING
          activityEnergyCost {
            value: 0.4
            unit: ENERGY_MEASURE_UNIT_TYPE_KILOWATT_HOURS
          }
          energyProviders {
            description: "Meta data-center, US-East"
            organization {
              name: "Meta"
              address {
                country: "United States"
                region: "New Jersey"
                locality: "Newark"
              }
            }
            energySource: ENERGY_SOURCE_TYPE_NATURAL_GAS
            energyProvided {
              value: 0.4
              unit: ENERGY_MEASURE_UNIT_TYPE_KILOWATT_HOURS
            }
          }
          co2CostEquivalent {
            value: 31.22
            unit: CO2_MEASURE_UNIT_TYPE_TONNES_CO2_EQUIVALENT
          }
          co2CostOffset {
            value: 31.22
            unit: CO2_MEASURE_UNIT_TYPE_TONNES_CO2_EQUIVALENT
          }
        }
      }
    }
  }
}
