# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:7dc07ac8-7fb8-4782-bf89-4762394e189d"
metadata: {
  component: {
    bom_ref: "my-app"
    type: CLASSIFICATION_APPLICATION
    name: "My Application"
  }
}
components: {
  bom_ref: "os"
  type: CLASSIFICATION_OPERATING_SYSTEM
  name: "Ubuntu"
  version: "24.04"
  description: "Ubuntu 24.04"
  isExternal: true
}
dependencies: {
  ref: "my-app"
  dependencies: {
    ref: "os"
  }
}
dependencies: {
  ref: "os"
}
