# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:e8c355aa-2142-4084-a8c7-6d42c8610ba2"

metadata: {
  timestamp: { seconds: 1704801600 }
  component: {
    type: CLASSIFICATION_APPLICATION
    name: "my application"
    version: "1.0"
  }
}

components: {
  name: "google.com"
  type: CLASSIFICATION_CRYPTOGRAPHIC_ASSET
  bom_ref: "c9c7ac91-2115-45e8-ae13-7d0e1dec74be"
  cryptoProperties: {
    assetType: CRYPTO_ASSET_TYPE_CERTIFICATE
    certificateProperties: {
      serialNumber: "1234567890ABCDEF"
      subjectName: "CN = www.google.com"
      issuerName: "C = US O = Google Trust Services LLC CN = GTS CA 1C3"
      notValidBefore: { seconds: 1479715200 }
      notValidAfter: { seconds: 1511337599 }
      certificateFormat: "X.509"
      certificateFileExtension: "crt"
      fingerprint: {
        alg: HASH_ALG_SHA_256
        value: "1e15e0fbd3ce95bde5945633ae96add551341b11e5bae7bba12e98ad84a5beb4"
      }
      certificateState: {
        predefined_state: PREDEFINED_STATE_ACTIVE
        reason: "Certificate is currently valid and in use"
      }
      creationDate: { seconds: 1479713400 }
      activationDate: { seconds: 1479715200 }
      relatedCryptographicAssets: {
        assets: {
          type: "algorithm"
          ref: "6b00f384-6c39-420f-91eb-94de0f7be569RR"
        }
        assets: {
          type: "publicKey"
          ref: "ceb37320-8239-40e8-ab77-8798dbd98773"
        }
      }
    }
    oid: "2.5.4.3"
  }
}

components: {
  name: "SHA512withRSA"
  type: CLASSIFICATION_CRYPTOGRAPHIC_ASSET
  bom_ref: "6b00f384-6c39-420f-91eb-94de0f7be569"
  cryptoProperties: {
    assetType: CRYPTO_ASSET_TYPE_ALGORITHM
    algorithmProperties: {
      primitive: CRYPTO_PRIMITIVE_SIGNATURE
      executionEnvironment: CRYPTO_EXECUTION_ENVIRONMENT_SOFTWARE_PLAIN_RAM
      implementationPlatform: CRYPTO_IMPLEMENTATION_PLATFORM_X86_64
      certificationLevel: "none"
      padding: CRYPTO_ALGORITHM_PADDING_PKCS1V15
      cryptoFunctions: CRYPTO_ALGORITHM_FUNCTION_SIGN
      cryptoFunctions: CRYPTO_ALGORITHM_FUNCTION_VERIFY
    }
    oid: "1.2.840.113549.1.1.13"
  }
}

components: {
  name: "RSA-2048"
  type: CLASSIFICATION_CRYPTOGRAPHIC_ASSET
  bom_ref: "ceb37320-8239-40e8-ab77-8798dbd98773"
  cryptoProperties: {
    assetType: CRYPTO_ASSET_TYPE_RELATED_CRYPTO_MATERIAL
    relatedCryptoMaterialProperties: {
      type: CRYPTO_RELATED_TYPE_PUBLIC_KEY
      id: "2e9ef09e-dfac-4526-96b4-d02f31af1b22"
      state: CRYPTO_RELATED_STATE_ACTIVE
      size: 2048
      format: "PEM"
      value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...\n-----END PUBLIC KEY-----"
      creationDate: { seconds: 1479715200 }
      activationDate: { seconds: 1479716400 }
      updateDate: { seconds: 1479715200 }
      expirationDate: { seconds: 1511337599 }
      securedBy: {
        mechanism: "None"
      }
      fingerprint: {
        alg: HASH_ALG_SHA_256
        value: "a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456"
      }
      relatedCryptographicAssets: {
        assets: {
          type: "algorithm"
          ref: "a154af0a-0dca-4ed5-b611-2405a3a6ae47"
        }
      }
    }
    oid: "1.2.840.113549.1.1.1"
  }
}

components: {
  name: "RSA-2048"
  type: CLASSIFICATION_CRYPTOGRAPHIC_ASSET
  bom_ref: "a154af0a-0dca-4ed5-b611-2405a3a6ae47"
  cryptoProperties: {
    assetType: CRYPTO_ASSET_TYPE_ALGORITHM
    algorithmProperties: {
      primitive: CRYPTO_PRIMITIVE_PKE
      algorithmFamily: "RSAES-OAEP"
      parameterSetIdentifier: "2048"
      executionEnvironment: CRYPTO_EXECUTION_ENVIRONMENT_SOFTWARE_PLAIN_RAM
      implementationPlatform: CRYPTO_IMPLEMENTATION_PLATFORM_X86_64
      certificationLevel: "none"
      padding: CRYPTO_ALGORITHM_PADDING_OAEP
      cryptoFunctions: CRYPTO_ALGORITHM_FUNCTION_ENCRYPT
      cryptoFunctions: CRYPTO_ALGORITHM_FUNCTION_DECRYPT
    }
    oid: "1.2.840.113549.1.1.1"
  }
}

components: {
  name: "TLS 1.3 Protocol"
  type: CLASSIFICATION_CRYPTOGRAPHIC_ASSET
  bom_ref: "a3553dc1-f376-43d1-89dc-87bb71981c0c"
  cryptoProperties: {
    assetType: CRYPTO_ASSET_TYPE_PROTOCOL
    protocolProperties: {
      type: CRYPTO_PROTOCOL_TYPE_TLS
      version: "1.3"
      cipherSuites: {
        name: "TLS_AES_256_GCM_SHA384"
        algorithms: "1977d71b-8981-4292-b40d-842a019c2229"
        algorithms: "422fa336-b401-42b7-89b8-8966aa30bca0"
        identifiers: "0x130x02"
      }
      cipherSuites: {
        name: "TLS_CHACHA20_POLY1305_SHA256"
        algorithms: "1af4fc08-5d0d-436e-8058-eeef921983d0"
        algorithms: "6af3066b-ab66-4593-975f-d9ba2c623a89"
        identifiers: "0x130x03"
      }
    }
    oid: "1.3.6.1.5.5.7.3.1"
  }
}
