# proto-file: schema/bom-1.7.proto
# proto-message: Bom

# All license posture in here is for show-case ony.
# This is not a real law-case!

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:df628836-6b9b-41c9-a724-b44743c54d42"
metadata: {
  lifecycles: { phase: LIFECYCLE_PHASE_DESIGN }
}
components: {
  type: CLASSIFICATION_LIBRARY
  group: "com.example"
  name: "situation-A"
  version: "1"
  description: "Multiple licenses: declared ids/names, and a concluded expression"
  licenses: {
    license: {
      id: "MIT"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
    }
  }
  licenses: {
    license: {
      id: "PostgreSQL"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
    }
  }
  licenses: {
    license: {
      name: "Apache Software License"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
    }
  }
  licenses: {
    expression: "(MIT OR PostgreSQL OR Apache-2.0)"
    acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_CONCLUDED
  }
}
components: {
  type: CLASSIFICATION_LIBRARY
  group: "com.example"
  name: "situation-B"
  version: "1"
  description: "Multiple license expressions: one declared, one concluded"
  licenses: {
    expression: "MIT OR (GPL-3.0 OR GPL-2.0)"
    acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
  }
  licenses: {
    expression: "(GPL-3.0-only AND LGPL-2.0-only)"
    acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_CONCLUDED
  }
}
components: {
  type: CLASSIFICATION_LIBRARY
  group: "com.example"
  name: "situation-C"
  version: "1"
  description: "Multiple license: one declared expression, one concluded id"
  licenses: {
    expression: "GPL-3.0-or-later OR GPL-2.0"
    acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
  }
  licenses: {
    license: {
      id: "GPL-3.0-only"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_CONCLUDED
    }
  }
}
components: {
  type: CLASSIFICATION_LIBRARY
  group: "com.example"
  name: "situation-D"
  version: "1"
  description: "Multiple license with texts: one declared expression, one concluded id"
  licenses: {
    acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
    expression_detailed: {
      expression: "GPL-3.0-or-later OR GPL-2.0"
      details: {
        license_identifier: "GPL-3.0-or-later"
        text: {
          value: "specific GPL-3.0-or-later license text"
        }
      }
      details: {
        license_identifier: "GPL-2.0"
        text: {
          value: "specific GPL-2.0 license text"
        }
      }
    }
  }
  licenses: {
    license: {
      id: "GPL-3.0-only"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_CONCLUDED
      text: {
        value: "specific GPL-3.0-or-later license text"
      }
    }
  }
}

components: {
  type: CLASSIFICATION_LIBRARY
  group: "com.example"
  name: "situation-E"
  version: "1"
  description: "Multiple licenses with urls: declared ids/names, and a concluded expression"
  licenses: {
    license: {
      id: "MIT"
      url: "https://example.com/licenses/MIT"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
    }
  }
  licenses: {
    license: {
      id: "PostgreSQL"
      url: "https://example.com/licenses/PostgreSQL"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
    }
  }
  licenses: {
    license: {
      name: "Apache Software License"
      url: "https://example.com/licenses/Apache-2.0"
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_DECLARED
    }
  }
  licenses: {
    expression_detailed: {
      acknowledgement: LICENSE_ACKNOWLEDGEMENT_ENUMERATION_CONCLUDED
      expression: "(MIT AND PostgreSQL AND Apache-2.0)"
      details: {
        license_identifier: "MIT"
        url: "https://example.com/licenses/MIT"
      }
      details: {
        license_identifier: "PostgreSQL"
        url: "https://example.com/licenses/PostgreSQL"
      }
      details: {
        license_identifier: "Apache-2.0"
        url: "https://example.com/licenses/Apache-2.0"
      }
    }
  }
}
