# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:78a32681-a31f-4097-b151-7b771cc58157"
components: {
  type: CLASSIFICATION_LIBRARY
  publisher: "Acme Inc"
  group: "com.acme"
  name: "cryptographic-provider"
  version: "2.2.0"
  licenses: {
    expression_detailed: {
      bom_ref: "acme-license-1"
      expression: "LicenseRef-AcmeCommercialLicense"
      licensing: {
        altIds: "acme"
        altIds: "acme-license"
        licensor: {
          organization: {
            name: "Acme Inc"
            contact: {
              name: "Acme Licensing Fulfillment"
              email: "licensing@example.com"
            }
          }
        }
        licensee: {
          organization: {
            name: "Example Co."
          }
        }
        purchaser: {
          individual: {
            name: "Samantha Wright"
            email: "samantha.wright@gmail.com"
            phone: "800-555-1212"
          }
        }
        purchaseOrder: "PO-12345"
        licenseTypes: LICENSING_TYPE_APPLIANCE
        lastRenewal: {
          seconds: 1649881239
          nanos: 3
        }
        expiration: {
          seconds: 1681417239
          nanos: 3
        }
      }
    }
  }
}
