# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components: {
  type: CLASSIFICATION_LIBRARY
  name: "my-json-parser"
  version: "1.0"
  tags: "json-parser"
  tags: "javascript"
  tags: "node.js"
}
services: {
  name: "my service"
  endpoints: "https://example.com/myservice"
  tags: "microservice"
  tags: "golang"
  tags: "aws"
  tags: "us-east-1"
}
