# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:bdd25550-f1c1-4cb4-b406-0c8d05ad6382"
metadata: {
  component: {
    bom_ref: "my-app"
    type: CLASSIFICATION_APPLICATION
    name: "My Application"
  }
}
components: {
  bom_ref: "libcurl"
  type: CLASSIFICATION_LIBRARY
  name: "libcurl"
  versionRange: "vers:generic/>=8.7.1|<9.0.0"
  description: "libcurl ^8.7.1"
  isExternal: true
}
dependencies: {
  ref: "my-app"
  dependencies: {
    ref: "libcurl"
  }
}
dependencies: {
  ref: "libcurl"
}
