# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
metadata: {
  component: {
    bom_ref: "my-app"
    type: CLASSIFICATION_APPLICATION
    name: "My Application"
  }
}
components: {
  bom_ref: "os"
  type: CLASSIFICATION_OPERATING_SYSTEM
  name: "Windows 11 (64bit)"
  description: "any Windows 11"
  isExternal: true
}
dependencies: {
  ref: "my-app"
  dependencies: {
    ref: "os"
  }
}
dependencies: {
  ref: "os"
}
