# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components: [
  {
    type: CLASSIFICATION_CRYPTOGRAPHIC_ASSET
    bom_ref: "9AADCCE0-F5AD-4A26-A1A9-5B3C85323E9B"
    name: "example-certificate.example.com"
    cryptoProperties: {
      assetType: CRYPTO_ASSET_TYPE_CERTIFICATE
      certificateProperties: {
        serialNumber: "AABBCCDDEEFF00112233"
        subjectName: "CN = example.example.com, OU = Security, O = Example Corp, C = US"
        issuerName: "CN = Example CA, O = Example Corp, C = US"
        notValidBefore {
          seconds: 1672531200  # 2023-01-01T00:00:00Z
        }
        notValidAfter {
          seconds: 1704067199  # 2023-12-31T23:59:59Z
        }
        certificateFormat: "X.509"
        certificateFileExtension: "pem"
        fingerprint {
          alg: HASH_ALG_SHA_256
          value: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
        }
        certificateState: [
          {
            predefined_state: PREDEFINED_STATE_ACTIVE
            reason: "Certificate is in active use"
          }
        ]
        creationDate {
          seconds: 1671091200  # 2022-12-15T10:00:00Z
        }
        activationDate {
          seconds: 1672531200  # 2023-01-01T00:00:00Z
        }
        certificateExtensions {
          extensions: [
            {
              commonExtension {
                name: COMMON_EXTENSION_NAME_BASIC_CONSTRAINTS
                value: "CA:FALSE"
              }
            },
            {
              commonExtension {
                name: COMMON_EXTENSION_NAME_KEY_USAGE
                value: "Digital Signature, Key Encipherment"
              }
            },
            {
              commonExtension {
                name: COMMON_EXTENSION_NAME_EXTENDED_KEY_USAGE
                value: "TLS Web Server Authentication, TLS Web Client Authentication"
              }
            },
            {
              commonExtension {
                name: COMMON_EXTENSION_NAME_SUBJECT_ALTERNATIVE_NAME
                value: "DNS:example.example.com, DNS:www.example.example.com"
              }
            },
            {
              customExtension {
                name: "environmentType"
                value: "Production"
              }
            }
          ]
        }
      }
      oid: "2.5.4.3"
    }
  }
]