# proto-file: schema/bom-1.7.proto
# proto-message: Bom

spec_version: "1.7"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
declarations: {
  assessors: {
    bom_ref: "assessor-1"
    thirdParty: true
    organization: {
      name: "Assessors Inc"
    }
  }
  attestations: {
    summary: "Attestation summary here"
    assessor: "assessor-1"
    map: {
      requirement: "requirement-1"
      claims: "claim-1"
      counterClaims: "counterClaim-1"
      conformance: {
        score: 0.8
        rationale: "Conformance rationale here"
        mitigationStrategies: "mitigationStrategy-1"
      }
      confidence: {
        score: 1
        rationale: "Confidence rationale here"
      }
    }
  }
  claims: {
    bom_ref: "claim-1"
    target: "acme-inc"
    predicate: "Predicate here"
    mitigationStrategies: "mitigationStrategy-1"
    reasoning: "Reasoning here"
    evidence: "evidence-1"
    counterEvidence: "counterEvidence-1"
    externalReferences: {
      type: EXTERNAL_REFERENCE_TYPE_ISSUE_TRACKER
      url: "https://alm.example.com"
    }
  }
  evidence: {
    bom_ref: "evidence-1"
    propertyName: "internal.com.acme.someProperty"
    description: "Description here"
    data: {
      name: "Name of the data"
      contents: {
        attachment: {
          content_type: "text/plain"
          value: "Evidence here"
        }
      }
      classification: "PII"
      sensitiveData: "Describe sensitive data here"
    }
    created: {
      seconds: 1682380800
      nanos: 0
    }
    expires: {
      seconds: 1684972800
      nanos: 0
    }
    author: {
      name: "Mary"
    }
    reviewer: {
      name: "Jane"
    }
  }
  evidence: {
    bom_ref: "counterEvidence-1"
    propertyName: "internal.com.acme.someProperty"
    description: "Description here"
    data: {
      name: "Name of the data"
      contents: {
        attachment: {
          content_type: "text/plain"
          value: "Counter evidence here"
        }
      }
      classification: "Public"
      sensitiveData: "Describe sensitive data here"
    }
    created: {
      seconds: 1682380800
      nanos: 0
    }
    expires: {
      seconds: 1684972800
      nanos: 0
    }
    author: {
      name: "Mary"
    }
    reviewer: {
      name: "Jane"
    }
  }
  evidence: {
    bom_ref: "mitigationStrategy-1"
    propertyName: "internal.com.acme.someProperty"
    description: "Description here"
    data: {
      name: "Name of the data"
      contents: {
        attachment: {
          content_type: "text/plain"
          value: "Mitigation strategy here"
        }
      }
      classification: "Company Confidential"
      sensitiveData: "Describe sensitive data here"
    }
    created: {
      seconds: 1682380800
      nanos: 0
    }
    expires: {
      seconds: 1684972800
      nanos: 0
    }
    author: {
      name: "Mary"
    }
    reviewer: {
      name: "Jane"
    }
  }
  targets: {
    organizations: {
      bom_ref: "acme-inc"
      name: "Acme Inc"
    }
  }
  affirmation: {
    statement: "I certify, to the best of my knowledge, that all information is correct..."
    signatories: {
      name: "Tom"
      role: "CEO"
    }
    signatories: {
      name: "Jerry"
      role: "COO"
      organization: {
        name: "Acme Inc"
      }
      externalReference: {
        type: EXTERNAL_REFERENCE_TYPE_ELECTRONIC_SIGNATURE
        url: "https://example.com/coo-sig.png"
      }
    }

  }
}
