spec_version: "1.5"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
metadata {
  supplier {
    name: "Acme, Inc."
    url: "https://example.com"
    contact {
      name: "Acme Distribution"
      email: "distribution@example.com"
      bom_ref: "contact-1"
    }
    bom_ref: "supplier-1"
  }
}
