spec_version: "1.5"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_MACHINE_LEARNING_MODEL
  bom_ref: "component-a"
  group: "CompVis"
  name: "stable-diffusion"
  version: "1.4"
  modelCard: {
    modelParameters: {
      approach: {
        type: MODEL_PARAMETER_APPROACH_TYPE_SUPERVISED
      }
      task: "task goes here"
      architectureFamily: "the architecture family goes here"
      modelArchitecture: "The architecture of the model."
      datasets: {
        dataset: {
          type: COMPONENT_DATA_TYPE_DATASET
          name: "Training Data"
          contents: {
            url: "https://example.com/path/to/dataset"
          }
          classification: "public"
        }
      }
      inputs: {
        format: "string"
      }
      outputs: {
        format: "string"
      }
    }
    quantitativeAnalysis: {
      performanceMetrics: {
        type: "The type of performance metric"
        value: "The value of the performance metric"
        slice: "The name of the slice this metric was computed on. By default, assume this metric is not sliced"
        confidenceInterval: {
          lowerBound: "The lower bound of the confidence interval"
          upperBound: "The upper bound of the confidence interval"
        }
      }
    }
    considerations: {
      users: "Who are the intended users of the model?"
      useCases: "Who are the intended users of the model?"
      technicalLimitations: "What are the known technical limitations of the model? E.g. What kind(s) of data should the model be expected not to perform well on? What are the factors that might degrade model performance?"
      performanceTradeoffs: "What are the known tradeoffs in accuracy/performance of the model?"
      ethicalConsiderations: {
        name: "The name of the risk"
        mitigationStrategy: "Strategy used to address this risk"
      }
      fairnessAssessments: {
        groupAtRisk: "The groups or individuals at risk of being systematically disadvantaged by the model"
        benefits: "Expected benefits to the identified groups"
        harms: "Expected harms to the identified groups"
        mitigationStrategy: "With respect to the benefits and harms outlined, please describe any mitigation strategy implemented."
      }
    }
  }
}
