spec_version: "1.5"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  publisher: "Acme Inc"
  group: "org.example"
  name: "mylibrary",
  version: "1.0.0"
}
formulation: [
  {
    bom_ref: "formula-1"
    components: [
      {
        bom_ref: "component-1"
        type: CLASSIFICATION_PLATFORM
        name: "Pipeline controller image"
        version: "v0.47.0"
      }
    ]
    workflows: [
      {
        bom_ref: "workflow-1"
        uid: "8edb2b08-e2c7-11ed-b5ea-0242ac120002"
        name: "My workflow"
        description: "Workflow description here"
        resourceReferences: [
          {
            ref: "component-a"
          }
        ]
        tasks: [
          {
            bom_ref: "task-1"
            uid: "task-uid-1"
            name: "fetch-repository"
            taskTypes: [ TASK_TYPE_CLONE ]
            description: "Description here"
            resourceReferences: [
              {
                ref: "component-a"
              }
            ]
            taskTypes: [
              TASK_TYPE_CLONE, TASK_TYPE_BUILD
            ]
            trigger {
              bom_ref: "trigger-1"
              uid: "trigger-1"
              type: TRIGGER_TYPE_API
            }
            steps: [
              {
                name: "My step"
              }
            ]
            inputs: [
              {
                resource: {
                  ref: "component-a"
                }
              }
            ]
            outputs: [
              {
                resource: {
                  ref: "component-a"
                }
              }
            ]
            timeStart {
              seconds: 3173618478
              nanos: 3
            }
            timeEnd {
              seconds: 3173618478
              nanos: 3
            }
            workspaces: [
              {
                bom_ref: "workspace-1"
                uid: "workspace-uid-1"
                name: "workspace"
              }
            ]
            runtimeTopology: [
              {
                ref: "task-1"
                dependencies: [
                  {
                    ref: "task-2"
                  }
                ]
              }
            ]
          }
        ]
        taskDependencies: [
          {
            ref: "task-1"
            dependencies: [
              {
                ref: "task-2"
              }
            ]
          }
        ]
        taskTypes: [ TASK_TYPE_CLONE, TASK_TYPE_BUILD ]
        trigger: {
          bom_ref: "trigger-2"
          uid: "trigger-uid-2"
          name: "My trigger"
          description: "Description here"
          resourceReferences: [
            {
              ref: "component-a"
            }
          ]
          type: TRIGGER_TYPE_WEBHOOK
          event: {
            uid: "event-1"
            description: "Description here"
            timeReceived {
              seconds: 3173618478
              nanos: 3
            }
            data: {
              content_type: "text/plain"
              value: "Foo/Bar"
            }
            source: {
              ref: "component-g"
            }
            target: {
              ref: "component-h"
            }
            properties: [
              {
                name: "Foo"
                value: "Bar"
              }
            ]
          }
          conditions: [
            {
              description: "Description here"
              expression: "1 == 1"
              properties: [
                {
                  name: "Foo"
                  value: "Bar"
                }
              ]
            }
          ]
          timeActivated {
            seconds: 3173618478
            nanos: 3
          }
          inputs: [
            {
              resource: {
                ref: "component-10"
              }
              source: {
                ref: "component-11"
              }
              target: {
                ref: "component-12"
              }
            }
          ]
          outputs: [
            {
              resource: {
                ref: "component-14"
              }
              type: OUTPUT_TYPE_ARTIFACT
              source: {
                ref: "component-15"
              }
              target: {
                ref: "component-16"
              }
            }
          ]
        }
        properties: [
          {
            name: "Foo"
            value: "Bar"
          }
        ]
        steps: [
          {
            name: "My step"
            description: "Description here"
            commands: [
              {
                executed: "ls -las"
                properties: [
                  {
                    name: "Foo"
                    value: "Bar"
                  }
                ]
              }
            ]
            properties: [
              {
                name: "Foo"
                value: "Bar"
              }
            ]
          }
        ]
        inputs: [
          {
            environmentVars: [
              {
                property: {
                  name: "Foo"
                  value: "Bar"
                }
              }
            ]
          },
          {
            environmentVars: [
              {
                value: "FooBar"
              }
            ]
          },
          {
            environmentVars: [
              {
                property: {
                  name: "Foo"
                  value: "Bar"
                }
              },
              {
                value: "FooBar"
              }
            ]
          }
        ]
        outputs: [
          {
            environmentVars: [
              {
                property: {
                  name: "Foo"
                  value: "Bar"
                }
              }
            ]
          },
          {
            environmentVars: [
              {
                value: "FooBar"
              }
            ]
          },
          {
            environmentVars: [
              {
                property: {
                  name: "Foo"
                  value: "Bar"
                }
              },
              {
                value: "FooBar"
              }
            ]
          }
        ]
        timeStart {
          seconds: 3173618478
          nanos: 3
        }
        timeEnd {
          seconds: 3173618478
          nanos: 3
        }
        workspaces: [
          {
            bom_ref: "workspace-1"
            uid: "workspace-1"
            name: "My workspace"
            aliases: [ "default-workspace" ]
            description: "Description here"
            resourceReferences: [
              {
                ref: "component-t"
              }
            ]
            accessMode: ACCESS_MODE_READ_WRITE
            mountPath: "/tmp/workspace"
            managedDataType: "ConfigMap"
            volumeRequest: "requestedVolumeClaim"
            volume: {
              uid: "volume-1"
              name: "My volume"
              mode: VOLUME_MODE_FILESYSTEM
              path: "/"
              sizeAllocated: "10GB"
              persistent: true
              remote: false
            }
          }
        ]
        runtimeTopology: [
          {
            ref: "component-s"
            dependencies: [
              {
                ref: "component-r"
              }
            ]
          }
        ]
        properties: [
          {
            name: "Foo"
            value: "Bar"
          }
        ]
      }
    ]
  }
]
