spec_version: "1.5"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  publisher: "Acme Inc"
  group: "com.acme"
  name: "cryptographic-provider"
  version: "2.2.0"
  licenses {
    license {
      bom_ref: "acme-license-1"
      name: "Acme Commercial License"
      licensing {
        altIds: "acme"
        altIds: "acme-license"
        licensor {
          organization {
            name: "Acme Inc"
            contact {
              name: "Acme Licensing Fulfillment"
              email: "licensing@example.com"
            }
          }
        }
        licensee {
          organization {
            name: "Example Co."
          }
        }
        purchaser {
          individual {
            name: "Samantha Wright"
            email: "samantha.wright@gmail.com"
            phone: "800-555-1212"
          }
        }
        purchaseOrder: "PO-12345"
        licenseTypes: LICENSING_TYPE_APPLIANCE
        lastRenewal {
          seconds: 1649881239
          nanos: 3
        }
        expiration {
          seconds: 1681417239
          nanos: 3
        }
      }
    }
  }
}
