# proto-file: schema/bom-1.4.proto
# proto-message: Bom

spec_version: "1.4"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  publisher: "Acme Inc"
  group: "org.example"
  name: "mylibrary"
  version: "1.0.0"
  external_references {
    type: EXTERNAL_REFERENCE_TYPE_ADVISORIES
    url: "https://example.org/security/feed/csaf"
    comment: "Security advisories from the vendor"
  }
  external_references {
    type: EXTERNAL_REFERENCE_TYPE_BOM
    url: "https://example.org/support/sbom/portal-server/1.0.0"
    comment: "An external SBOM that describes what this component includes"
    hashes {
      alg: HASH_ALG_SHA_256
      value: "708f1f53b41f11f02d12a11b1a38d2905d47b099afc71a0f1124ef8582ec7313"
    }
  }
  external_references {
    type: EXTERNAL_REFERENCE_TYPE_DOCUMENTATION
    url: "https://example.org/support/documentation/portal-server/1.0.0"
    comment: "Vendor provided documentation for the product"
  }
}
