# proto-file: schema/bom-1.4.proto
# proto-message: Bom

spec_version: "1.4"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_APPLICATION
  name: "application-a"
  version: "1.0"
}
components {
  type: CLASSIFICATION_LIBRARY
  name: "library-a"
  version: "1.0"
}
components {
  type: CLASSIFICATION_FRAMEWORK
  name: "framework-a"
  version: "1.0"
}
components {
  type: CLASSIFICATION_CONTAINER
  name: "container-a"
  version: "1.0"
}
components {
  type: CLASSIFICATION_OPERATING_SYSTEM
  name: "operating-system-a"
  version: "1.0"
}
components {
  type: CLASSIFICATION_FIRMWARE
  name: "firmware-a"
  version: "1.0"
}
components {
  type: CLASSIFICATION_DEVICE
  name: "device-a"
  version: "1.0"
}
components {
  type: CLASSIFICATION_FILE
  name: "file-a"
  version: "1.0"
}
