# proto-file: schema/bom-1.4.proto
# proto-message: Bom

spec_version: "1.4"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  publisher: "Acme Inc"
  group: "com.acme"
  name: "tomcat-catalina"
  version: "9.0.14"
  licenses {
    license {
      id: "Apache-2.0"
    }
  }
}
