# proto-file: schema/bom-1.6.proto
# proto-message: Bom

spec_version: "1.6"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  name: "acme-example"
  version: "1.0.0"
  releaseNotes: {
    type: "major"
    title: "My new release"
    featuredImage: "https://example.com/featured_image.png"
    socialImage: "https://example.com/social_image.png"
    description: "The main description of your release"
    aliases: "Project Orion"
    tags: "CMS"
    tags: "SEO"
    tags: "wysiwyg"
    resolves {
      type: ISSUE_CLASSIFICATION_ENHANCEMENT
      id: "JIRA-17240"
      description: "Great new feature that does something"
      source {
        name: "Acme Org"
        url: "https://issues.acme.org/17240"
      }
    }
    resolves {
      type: ISSUE_CLASSIFICATION_SECURITY
      id: "CVE-2019-9997"
      name: "CVE-2019-9997"
      description: "Great new feature that does something"
      source {
        name: "NVD"
        url: "https://nvd.nist.gov/vuln/detail/CVE-2019-9997"
      }
    }
  }
}
services {
  bom_ref: "b2a46a4b-8367-4bae-9820-95557cfe03a8"
  provider {
    name: "Partner Org"
    url: "https://partner.org"
    contact {
      name: "Support"
      email: "support@partner"
      phone: "800-555-1212"
    }
  }
  group: "org.partner"
  name: "Stock ticker service"
  version: "2020-Q2"
  description: "Provides real-time stock information"
  endpoints: "https://partner.org/api/v1/lookup"
  endpoints: "https://partner.org/api/v1/stock"
  authenticated: true
  x_trust_boundary: true
  data {
    flow: DATA_FLOW_INBOUND
    value: "PII"
  }
  data {
    flow: DATA_FLOW_OUTBOUND
    value: "PIFI"
  }
  data {
    flow: DATA_FLOW_BI_DIRECTIONAL
    value: "public"
  }
  data {
    flow: DATA_FLOW_UNKNOWN
    value: "partner-data"
  }
  licenses {
    license {
      name: "Partner license"
    }
  }
  external_references {
    type: EXTERNAL_REFERENCE_TYPE_WEBSITE
    url: "http://partner.org"
  }
  external_references {
    type: EXTERNAL_REFERENCE_TYPE_DOCUMENTATION
    url: "http://api.partner.org/swagger"
  }
  releaseNotes: {
    type: "major"
    title: "My new release"
    featuredImage: "https://example.com/featured_image.png"
    socialImage: "https://example.com/social_image.png"
    description: "The main description of your release"
    aliases: "Project Orion"
    tags: "CMS"
    tags: "SEO"
    tags: "wysiwyg"
    resolves {
      type: ISSUE_CLASSIFICATION_ENHANCEMENT
      id: "JIRA-17240"
      description: "Great new feature that does something"
      source {
        name: "Acme Org"
        url: "https://issues.acme.org/17240"
      }
    }
    resolves {
      type: ISSUE_CLASSIFICATION_SECURITY
      id: "CVE-2019-9997"
      name: "CVE-2019-9997"
      description: "Great new feature that does something"
      source {
        name: "NVD"
        url: "https://nvd.nist.gov/vuln/detail/CVE-2019-9997"
      }
    }
  }
}
