# proto-file: schema/bom-1.6.proto
# proto-message: Bom

spec_version: "1.6"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
metadata {
  lifecycles [
    {
      phase: LIFECYCLE_PHASE_BUILD
    },
    {
      phase: LIFECYCLE_PHASE_POST_BUILD
    },
    {
      name: "platform-integration-testing"
      description: "Integration testing specific to the runtime platform"
    }
  ]
}
