# proto-file: schema/bom-1.6.proto
# proto-message: Bom

spec_version: "1.6"
version: 1
serial_number: "urn:uuid:ed5c5ba0-2be6-4b58-ac29-01a7fd375123"
components {
  component {
    type: CLASSIFICATION_MACHINE_LEARNING_MODEL
    bom_ref: "huggingface.co-meta-llama-Llama-2-7b"
    name: "meta-llama/Llama-2-7b"
    supplier {
      name: "Hugging Face"
    }
    supplier {
      name: "meta"
    }
    modelCard: {
      considerations: {
        environmentalConsiderations: {
          energyConsumptions: {
            energyConsumption: {
              activity: "training"
              activityEnergyCost: {
                value: 0.4
                unit: "kWh"
              }
              energyProviders: {
                energyProvider: {
                  name: "Meta data-center, US-East"
                  energySource: "natural-gas"
                  energyProvided: {
                    value: 0.4
                    unit: "kWh"
                  }
                }
              }
              co2CostEquivalent: {
                value: 31.22
                unit: "tCO2eq"
              }
              co2CostOffset: {
                value: 31.22
                unit: "tCO2eq"
              }
            }
          }
        }
      }
    }
  }
}