spec_version: "1.3"
version: 1
serial_number: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
components {
  type: CLASSIFICATION_LIBRARY
  name: "acme-library-a"
  version: "1.0.0"
  components {
    type: CLASSIFICATION_LIBRARY
    name: "acme-library-b"
    version: "2.0.0"
  }
}
services {
  name: "acme-service-a"
  services {
    name: "acme-service-b"
  }
}
