# docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CT CDX-1.x JavaScript

on:
  push:
    branches: ['master', 'main']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: tools/src/test/js/schema-v1

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  test_js:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Node.js
        # see https://github.com/actions/setup-node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.x'
          package-manager-cache: false
      - name: Install Dependencies
        run: npm install
      - name: Run test 
        run: npm test
