name: Zizmor

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
  push:
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
  schedule:
    - cron: '0 0 * * 6'

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Run zizmor
        # see https://github.com/zizmorcore/zizmor-action
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          advanced-security: false
          annotations: true
